### ISSUE TITLE
font dir missing

### ISSUE THREAD

**Issue by ksourdrille** [uroesch/asciidoctor-pdf-tutorial-theme#9]
hello, I tried to use your theme for asciidoc but I have an error 

![image](https://user-images.githubusercontent.com/100124349/194838265-6fd8dcb0-796e-4b15-ac69-d44c0a990456.png)

font directory after cloning 
![image](https://user-images.githubusercontent.com/100124349/194838344-30dfd667-02e7-425a-90b6-8f19e3596665.png)

**Comment by uroesch** [comment]
Hello Kélian ,

The font which seems to be missing on your system is part of the `asciidoctor-pdf` installation. It is a fallback or subset font shipped with `asciidoctor-pdf`

Can you tell me which version of `asciidoctor-pdf` you are using. I made this theme before the release of `asciidoctor-pdf` 2.0.x and haven't tested it against such a version fully.

But just to be sure I did a little test to confirm everything is working as it should. Here are the steps I took. 

```console
$ git clone https://github.com/uroesch/asciidoctor-pdf-tutorial-theme 
$ cd asciidoctor-pdf-tutorial-theme/
$ bundler init
$ echo 'gem "asciidoctor-pdf"' >> Gemfile
$ bundler config --local path vendor
$ bundler install
...
$ bundle exec asciidocotor-pdf --version

Asciidoctor PDF 2.3.2 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
$ bundle exec asciidoctor-pdf -a pdf-stylesdir=. -a pdf-style=tutorial.yaml -a pdf-fontsdir=fonts -a iconsdir=icons tests/book.adoc
```
Let me know if that brings you a bit further.

cheers, 

--urs

**Comment by ksourdrille** [comment]
Hello, thank you for your quick answer, I followed your steps, I have the same version as you now 
![image](https://user-images.githubusercontent.com/100124349/194858241-3c80fb8a-5568-4650-8b76-a788e6f5cfc5.png)

however when I want to generate a pdf I have the default theme of asciidoc and not yours, with this command line "bundle exec asciidoctor-pdf -a pdf-stylesdir=. -a pdf-style=tutorial.yml -a pdf-fontsdir=fonts -a iconsdir=icons myfile.adoc"

Regards,
Kélian

**Comment by uroesch** [comment]
Hello Kélian,

I just checked my command again and saw that I have a typo ☹️ it should be

`tutorial.yml` not `tutorial.yaml`

Also I saw that the syntax for the `pdf-xxxx` options have changed from `pdf-style` to `pdf-theme`.

For reference here the whole command corrected

```console
$ bundle exec asciidoctor-pdf \
  -a pdf-themesdir=. \
  -a pdf-theme=tutorial.yml \
  -a pdf-fontsdir=fonts \
  -a iconsdir=icons \
  myfile.adoc
```

cheers,

--urs

**Comment by ksourdrille** [comment]
Hello, i have following your steps and run this command 
`bundle exec asciidoctor-pdf -a pdf-stylesdir=. -a pdf-style=tutorial.yml -a pdf-fontsdir=fonts -a iconsdir=icons myfile.adoc`

and i have the default theme aswell... 

i don't know why 

content of my .adoc file : 

```
:source-highlighter: rouge
:icons: font


= test
:toc: 



[.landscape]
<<<

== test

IMPORTANT: test 

```

did i missed something ?

Kélian

**Comment by ksourdrille** [comment]
ok, it's my fault, i copied your command this one 

``` 
bundle exec asciidoctor-pdf -a pdf-stylesdir=. -a pdf-style=tutorial.yaml -a pdf-fontsdir=fonts -a iconsdir=icons tests/book.adoc 
```

and not the newest, sorry

EDIT : generate the PDF with your theme but without tittle page :(
